import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { apiPlugin, storyblokInit } from "@storyblok/react/rsc";
import { accessToken } from "~/variables";
import StoryblokProvider from "./StoryblokProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

storyblokInit({
  accessToken,
  use: [apiPlugin],
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoryblokProvider>
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </StoryblokProvider>
  );
}
